### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by LucasFinney** [LucasFinney/Hangman#1]
- [ ] Clean up the code. Put things into separate methods to reduce the amount of logic in the main loop
- [ ] Scoring system? More unique letters -> Higher difficulty
- [ ] Score counts down. A perfect play would mean that there were no incorrect guesses.
- [ ] Leaderboard
- [ ] Interpretation of inputs: make sure that case doesn't break things, refuse non-alphabetical inputs
- [ ] An ASCII hang-man
- [ ] Some kind of implementation better than a command-line program? Maybe even a... GUI?
